# Generated by Django 3.2.8 on 2021-10-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dim_sum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimsum',
            name='history',
            field=models.TextField(default='Write summary here.'),
        ),
    ]
