# Generated by Django 3.2.8 on 2021-10-24 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dim_sum', '0002_dimsum_history'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DimSum',
            new_name='DimSumItem',
        ),
    ]
