# Generated by Django 3.2.8 on 2021-10-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dim_sum', '0003_rename_dimsum_dimsumitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimsumitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dimsumitem',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dimsumitem',
            name='item_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dimsumitem',
            name='normal_price',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
    ]
