# Generated by Django 3.2.8 on 2021-10-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dim_sum', '0004_auto_20211023_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimsumitem',
            name='tasty',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
