# Generated by Django 3.2.8 on 2021-10-24 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dim_sum', '0005_dimsumitem_tasty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimsumitem',
            name='tasty',
        ),
    ]
