# Generated by Django 3.2.8 on 2021-10-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dim_sum', '0006_remove_dimsumitem_tasty'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimsumitem',
            name='tasty',
            field=models.BooleanField(default=True),
        ),
    ]
